name: ElectroMart Homepage CI

on:
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install npm dependencies
        run: |
          npm install --save-dev stylelint stylelint-config-standard

      # First, try auto-fixing errors
      - name: Lint and auto-fix CSS file
        run: npx stylelint styles.css --fix

      # Optionally, check again and fail if unfixable errors remain
      - name: Fail if lint errors remain
        run: npx stylelint styles.css
        continue-on-error: false

  deploy:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Staging (Simulated)
        run: echo "Deployment to staging successful!"