name: wsebsite

on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install npm dependencies
        run: |
          npm install --save-dev stylelint stylelint-config-standard

      - name: Lint CSS file and auto-fix
        run: npx stylelint styles.css --fix  # Automatically fix linting errors
